Repository enjin/platform-marketplace, pull requests merged in 2024-04, with the labels that each got.

#40 [PLA-1685] Add model owner
  src/Models/Laravel/MarketplaceBid.php
  src/Models/Laravel/MarketplaceListing.php
  src/Models/Laravel/MarketplaceSale.php
Labels: enhancement, Review effort [1-5]: 1

#41 [PLA-1706] Decoder changes on marketplace
  .github/CODEOWNERS
  .github/workflows/code_analysis.yml
  .github/workflows/run_tests.yml
  .php-cs-fixer.php
  composer.json
  lang/en/enum.php
  lang/en/type.php
  lang/en/validation.php
  pint.json
  src/GraphQL/Mutations/CreateListingMutation.php
  src/GraphQL/Queries/GetListingsQuery.php
  src/GraphQL/Types/MarketplaceListingType.php
  src/Models/Laravel/MarketplaceBid.php
  src/Models/Laravel/MarketplaceListing.php
  src/Models/Laravel/MarketplaceSale.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  src/Rules/EnoughTokenSupply.php
  src/Rules/MinimumPrice.php
  src/Services/Processor/Substrate/Codec/Codec.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingFilled.php
  src/Services/Processor/Substrate/Events/Implementations/MarketplaceSubstrateEvent.php
  tests/Feature/GraphQL/Mutations/CreateListingTest.php
  tests/Feature/GraphQL/TestCaseGraphQL.php
  tests/Feature/GraphQL/Traits/CreateCollectionData.php
Labels: documentation, enhancement, Review effort [1-5]: 3

#42 [PLA-1735] Adds skipValidation to blockchain transactions
  src/GraphQL/Mutations/CancelListingMutation.php
  src/GraphQL/Mutations/CreateListingMutation.php
  src/GraphQL/Mutations/FillListingMutation.php
  src/GraphQL/Mutations/FinalizeAuctionMutation.php
  src/GraphQL/Mutations/PlaceBidMutation.php
  tests/Feature/GraphQL/Mutations/CancelListingTest.php
  tests/Feature/GraphQL/Mutations/CreateListingTest.php
  tests/Feature/GraphQL/Mutations/FillListingTest.php
  tests/Feature/GraphQL/Mutations/FinalizeAuctionTest.php
  tests/Feature/GraphQL/Mutations/PlaceBidTest.php
  tests/Feature/GraphQL/Resources/CancelListing.graphql
  tests/Feature/GraphQL/Resources/CreateListing.graphql
  tests/Feature/GraphQL/Resources/FillListing.graphql
  tests/Feature/GraphQL/Resources/FinalizeAuction.graphql
  tests/Feature/GraphQL/Resources/PlaceBid.graphql
Labels: enhancement, Review effort [1-5]: 4
