Repository enjin/platform-marketplace, pull requests merged in 2024-01, with the labels that each got.

#30 [PLA-1536] Adds sync&ingest filter to marketplace
  src/Enums/Substrate/StorageKey.php
  src/Enums/Substrate/StorageType.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingFilled.php
  src/Services/Processor/Substrate/Parser.php
Labels: enhancement

#31 Add multi tenant
  src/Events/Substrate/Marketplace/AuctionFinalized.php
  src/Events/Substrate/Marketplace/BidPlaced.php
  src/Events/Substrate/Marketplace/ListingCancelled.php
  src/Events/Substrate/Marketplace/ListingCreated.php
  src/Events/Substrate/Marketplace/ListingFilled.php
  src/GraphQL/Queries/GetBidQuery.php
  src/GraphQL/Queries/GetListingQuery.php
  src/GraphQL/Queries/GetSaleQuery.php
  src/Models/Laravel/MarketplaceBid.php
  src/Models/Laravel/MarketplaceListing.php
  src/Models/Laravel/MarketplaceSale.php
  src/Rules/BidExists.php
  src/Rules/ListingExists.php
  src/Rules/SaleExists.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingFilled.php
Labels: Review effort [1-5]: 3

#33 [PLA-1577] Fixes collection filter on sync
  src/Services/Processor/Substrate/Parser.php
Labels: bug, Review effort [1-5]: 2, Bug fix
