Repository enjin/platform-marketplace, pull requests merged in 2024-06, with the labels that each got.

#46 [PLA-1804] Events broadcast & logs refactor
  src/Events/Substrate/Marketplace/AuctionFinalized.php
  src/Events/Substrate/Marketplace/BidPlaced.php
  src/Events/Substrate/Marketplace/ListingCancelled.php
  src/Events/Substrate/Marketplace/ListingCreated.php
  src/Events/Substrate/Marketplace/ListingFilled.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCancelled.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingFilled.php
  testbench.yaml
Labels: bug, enhancement, Bug fix, Review effort [1-5]: 4

#47 [PLA-1806] Adds event model to ListingCreated / AuctionFinalized / BidPlaced
  src/Events/Substrate/Marketplace/AuctionFinalized.php
  src/Events/Substrate/Marketplace/BidPlaced.php
  src/Events/Substrate/Marketplace/ListingCreated.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
  testbench.yaml
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#48 [PLA-1806] Fixes missing function arguments
  src/Enums/Substrate/MarketplaceEventType.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#49 [PLA-1806] Class init error
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/AuctionFinalized.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/BidPlaced.php
  src/Services/Processor/Substrate/Events/Implementations/Marketplace/ListingCreated.php
Labels: Review effort [1-5]: 2, Bug fix

#52 [PLA-1678] Laravel 11 update.
  .github/workflows/run_tests.yml
  composer.json
  phpunit.xml
  src/Enums/Substrate/StorageKey.php
  src/Models/Laravel/MarketplaceBid.php
  src/Models/Laravel/MarketplaceListing.php
  src/Models/Laravel/MarketplaceSale.php
  src/Models/Laravel/Wallet.php
  src/Models/MarketplaceBid.php
  src/Models/MarketplaceListing.php
  src/Models/MarketplaceSale.php
  src/Models/MarketplaceState.php
  src/Models/Substrate/AuctionDataParams.php
  src/Models/Substrate/MultiTokensTokenAssetIdParams.php
  src/Rules/ListingExists.php
  src/Rules/TokenExistsInCollection.php
  testbench.yaml
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#54 [PLA-1693] Set path for improved local testing.
  src/MarketplaceServiceProvider.php
Labels: enhancement, Review effort [1-5]: 2

#55 [PLA-1693] Improved local testing tweaks.
  src/MarketplaceServiceProvider.php
  src/Package.php
Labels: enhancement, Review effort [1-5]: 2
